### ISSUE TITLE
Installing via Bower doesn't install the latest

### ISSUE THREAD

**Issue by brunck** [robgallen/moment-fquarter#16]
When using Bower to install moment-fquarter, it's installing an older version of the code, one that doesn't include PR #11 's changes.
Is there something that needs to be updated to make this work?

**Comment by robgallen** [comment]
Have updated version numbers and created new release. Please could you see if this fixes the issue?

**Comment by brunck** [comment]
Could you address PR #11 ? The start and end dates currently do not work and this PR fixes the problem.

**Comment by robgallen** [comment]
Assume you mean PR #15 ? I've just merged this.
