### ISSUE TITLE
npm install fails in project without bower

### ISSUE THREAD

**Issue by cdmcmahon** [robgallen/moment-fquarter#19]
Does this package expect bower to be installed, even if installing via npm? I get the following error trying to install.

```npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! moment-fquarter@0.1.0 postinstall: `bower install`
npm ERR! spawn ENOENT```

**Comment by robgallen** [comment]
I'll look into this when I get back from half term. Iirc, this was from a fork, I don't use bower.

**Comment by robgallen** [comment]
Have (hopefully) removed dependency on Bower and published to NPM.
