### ISSUE TITLE
Calculate day to next Fiscal Quarters

### ISSUE THREAD

**Issue by git001** [robgallen/moment-fquarter#20]
I have created a issue request on atom-clock with the same question.

https://github.com/b3by/atom-clock/issues/37

so when I have a glue how to solve this question with moment-fquarter maybe there then will also be a solution for atom-clock.

**Comment by ftm** [comment]
I've just had a play around, there seems to be an undocumented feature of `moment-fquarter` which is that when using the `.fquarter()` function, included the returned object are the dates the quarter ends and begins as `start` and `end`, for example:

```javascript
moment("2017-07-03").fquarter()
```
returns
```javascript
{
  quarter: 2, 
  year: 2017, 
  nextYear: 2018, 
  start: "2017-07-01", 
  end: "2017-09-30"
}
``` 

So you can then use the end date with [`moment().diff()`](https://momentjs.com/docs/#/displaying/difference/) to calculate the number of days until the start of the next quarter, for example:

```javascript
var now = moment()
var thisQuarterEnd = moment().fquarter().end
var nextQuarterStart = moment(thisQuarterEnd).add(1, 'd')
var daysUntilNextQuarter = Math.ceil(nextQuarterStart.diff(now, 'd', true))

console.log(now.format("YYYY-MM-DD"))
console.log(nextQuarterStart.format("YYYY-MM-DD"))
console.log(daysUntilNextQuarter + " days")
```
returns
```
2017-07-03
2017-10-01
90 days
```

You can see the code running [here](https://runkit.com/embed/kmvan7fojgy0)

**Comment by git001** [comment]
wow you are great thanks.

**Comment by robgallen** [comment]
Nice - you beat me to it!
https://jsfiddle.net/robgallen/s7bbv80s/

Think the start/end was a pull request. I really should update the docs!
